<script lang="ts">import snippets from '$lib/plugins/guide-snippets.json';</script>
<svelte:head><title>个人插件开发与 API · Warcon China</title></svelte:head>
<main class="mx-auto max-w-5xl px-5 py-10">
<div class="flex flex-wrap gap-3"><a class="btn" href="/plugins">← 个人插件</a><a class="btn" href="/examples/plugins/server-cards.json" download>下载 JSON 示例</a><a class="btn" href="/examples/plugins/round-summary.zip" download>下载代码示例</a><a class="btn" href="/docs/personal-plugins.zh-CN.md" download>下载完整文档</a></div>
<h1 class="mt-8 text-xl font-semibold text-white">Warcon China 个人插件开发与接入（API v1）</h1>
<h2 class="mt-8 text-xl font-semibold text-white">1. 先选一种方式</h2>
<div class="table-wrap mt-4"><table><thead><tr><th>方式</th><th>适用情况</th><th>如何安装</th></tr></thead><tbody><tr><td>JSON 卡片</td><td>想自己调整数据卡片、玩家表格、文字和强调色</td><td>登录后打开“个人插件”，导入 JSON，选择服务器，保存</td></tr><tr><td>Svelte + TypeScript 组件</td><td>需要自定义布局、图表或交互</td><td>开发者把组件加入源码、注册并重新构建；用户在“个人插件”选用</td></tr></tbody></table></div>
<p class="mt-3 leading-7 text-mist-300">两种方式都按账号保存配置，最多 20 个。插件不会获得额外服务器权限。中文界面沿用面板样式；代码组件使用同一套 Svelte 5、TypeScript、Tailwind CSS 4 和项目锁文件，不单独加载另一套 Svelte、React 或全局 CSS。</p>
<p class="mt-3 leading-7 text-mist-300">第一版提供展示插件，不提供上传 JS 后在服务器执行、动态安装 npm 包、Worker 后台任务或自动处罚挂钩。代码插件属于受信任的面板源码，部署者需审查；它不是沙箱。JSON 只能选择固定组件和样式字段，不执行 HTML、CSS 或 JavaScript。</p>
<h2 class="mt-8 text-xl font-semibold text-white">2. 不写代码：一步一步安装 JSON 插件</h2>
<p class="mt-3 leading-7 text-mist-300">1. 登录 Warcon China。</p>
<p class="mt-3 leading-7 text-mist-300">2. 点击顶部导航“个人插件”（小屏幕在账号菜单内）。</p>
<p class="mt-3 leading-7 text-mist-300">3. 点击“下载 JSON 示例”，或直接用“新建 JSON 示例”。</p>
<p class="mt-3 leading-7 text-mist-300">4. 如果已有文件，点击“导入 JSON”，选 UTF-8 编码的 <code>.json</code> 文件，最大 64 KB。</p>
<p class="mt-3 leading-7 text-mist-300">5. 修改插件名称和说明，选强调色、1～3 列以及舒适／紧凑间距。</p>
<p class="mt-3 leading-7 text-mist-300">6. 在“关联服务器”选择有权限查看的服务器；不选服务器时，静态文字可正常展示，数据指标显示“—”。</p>
<p class="mt-3 leading-7 text-mist-300">7. 在 JSON 的 <code>widgets</code> 中增删卡片，最多 12 个。标识 <code>id</code> 用 2～48 位小写字母、数字、连字符，并以字母开头。自己的两个插件不能使用同一个标识。</p>
<p class="mt-3 leading-7 text-mist-300">8. 若在 JSON 中修改了名称、说明、样式，点“应用 JSON 到表单”；保存以表单为准。</p>
<p class="mt-3 leading-7 text-mist-300">9. 保持“启用插件”勾选，点击“保存插件”。</p>
<p class="mt-3 leading-7 text-mist-300">10. 在上方“我的插件”点击“打开插件”。可见页面每 10 秒刷新，隐藏标签页暂停自动刷新。</p>
<p class="mt-3 leading-7 text-mist-300">11. 分享时点“导出 JSON”。导出的仅是清单和样式，不含服务器关联、登录会话或密钥；接收者需自行导入并选择服务器。</p>
<p class="mt-3 leading-7 text-mist-300">启停与删除只影响自己的配置。删除插件配置不会删除服务器，也不会卸载已编译的代码组件。代码组件需要由部署者从注册表移除、重新构建才能卸载。</p>
<h2 class="mt-8 text-xl font-semibold text-white">3. 完整 JSON 示例</h2>
<p class="mt-3 leading-7 text-mist-300">下载：<code>/examples/plugins/server-cards.json</code>。</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[0]}</code></pre>
<h3 class="mt-8 text-xl font-semibold text-white">字段约定</h3>
<p class="mt-3 leading-7 text-mist-300">- <code>apiVersion</code>：目前只能填 <code>1</code>。<code>version</code> 是插件自身版本，格式 <code>1.0.0</code>。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>renderer</code>：JSON 使用 <code>cards</code>；代码插件使用已注册组件的名字，如 <code>round-summary</code>。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>style.accent</code>：六位十六进制颜色，例如 <code>#69d6e3</code>；<code>columns</code> 是 1、2、3；<code>density</code> 是 <code>comfortable</code> 或 <code>compact</code>。代码插件可选择使用这些参数，实际支持情况由组件决定。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>metric</code> 数据卡片支持 <code>online</code> 在线人数、<code>kills</code> 在线玩家总击杀、<code>deaths</code> 在线玩家总死亡、<code>cash</code> 在线玩家总现金、<code>averagePing</code> 已知延迟的平均值（ms）。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>players.columns</code> 支持 <code>name</code>、<code>steamId</code>、<code>faction</code>、<code>kills</code>、<code>deaths</code>、<code>cash</code>、<code>ping</code>。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>players.limit</code>：1～50，默认 10；<code>sortBy</code> 支持 <code>kills</code>、<code>deaths</code>、<code>cash</code>、<code>ping</code>，降序，默认 <code>kills</code>。</p>
<p class="mt-3 leading-7 text-mist-300">- <code>text.text</code>：纯文本，最长 2,000 字符；不会解析 HTML。</p>
<p class="mt-3 leading-7 text-mist-300">- 名称和组件标题最多 80 字符，说明最多 500 字符。不接受未知字段、外部 URL、脚本或任意 CSS。</p>
<p class="mt-3 leading-7 text-mist-300">总击杀、总死亡、总现金来自当前在线玩家快照，不能解释为整场比赛总量；离线玩家不包含在内。现金是当前余额，不是赚钱效率。缺少数据时使用 JSON <code>null</code> 和界面“—”，不伪造为 0。玩家列表上限 256，超过上限会标记 <code>playersTruncated</code> 并将合计值与平均延迟设为 null。</p>
<h2 class="mt-8 text-xl font-semibold text-white">4. 编写 Svelte + TypeScript 代码插件</h2>
<p class="mt-3 leading-7 text-mist-300">项目已经包含可以直接启用的例子：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[1]}</code></pre>
<h3 class="mt-8 text-xl font-semibold text-white">4.1 创建文件</h3>
<p class="mt-3 leading-7 text-mist-300">把 <code>round-summary</code> 文件夹复制为 <code>my-summary</code>。修改清单中的 <code>id</code> 和 <code>renderer</code> 为 <code>my-summary</code>，名称改成“我的概况”。保留 <code>apiVersion: 1</code>，代码组件可使用空的 <code>widgets: []</code>。</p>
<h3 class="mt-8 text-xl font-semibold text-white">4.2 编写组件</h3>
<p class="mt-3 leading-7 text-mist-300">下面代码可放进 <code>src/lib/plugins/extensions/my-summary/Plugin.svelte</code>：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[2]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">组件通过 props 接收数据，不需要保存 API Key，也无需自行轮询。<code>snapshot</code> 在未关联服务器、权限失败或尚未加载时可以是 null。面板外层提供刷新按钮、过期提示及渲染错误边界。</p>
<h3 class="mt-8 text-xl font-semibold text-white">4.3 注册清单和组件</h3>
<p class="mt-3 leading-7 text-mist-300">在 <code>src/lib/plugins/catalog.ts</code> 增加导入，并把解析后的清单加进现有数组；保留原有示例：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[3]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">在 <code>src/lib/plugins/components.ts</code> 增加：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[4]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">两处的 renderer 名字必须一致。仅上传一份 <code>renderer: "my-summary"</code> 的 JSON，不会把组件代码安装到服务器；未注册会返回 <code>unknown_renderer</code>。</p>
<h3 class="mt-8 text-xl font-semibold text-white">4.4 保持语言和样式一致</h3>
<p class="mt-3 leading-7 text-mist-300">- 所有面向管理员的文案使用中文，字段标识使用稳定英文，不随显示语言改名。</p>
<p class="mt-3 leading-7 text-mist-300">- 复用项目的 <code>panel</code>、<code>btn</code>、<code>input</code>、<code>text-mist-400</code> 等类。</p>
<p class="mt-3 leading-7 text-mist-300">- 组件 CSS 写在自身 <code>&lt;style&gt;</code> 中，让 Svelte 自动作用域隔离。避免 <code>:global(body)</code>、全局 <code>button</code> 覆盖和固定顶层遮罩。</p>
<p class="mt-3 leading-7 text-mist-300">- CSS 变量使用 <code>--plugin-</code> 前缀，不覆盖面板主题变量。</p>
<p class="mt-3 leading-7 text-mist-300">- 不额外加载 CDN 框架、全局样式重置或另一版本 Svelte。依赖随仓库锁文件统一构建。</p>
<p class="mt-3 leading-7 text-mist-300">- 不使用 <code>&#123;@html&#125;</code> 渲染玩家昵称或导入文本；不把密钥放入清单、组件代码或浏览器本地存储。</p>
<p class="mt-3 leading-7 text-mist-300">- 若增加自己的后端 API，必须使用现有认证、CSRF、服务器权限校验；前端隐藏按钮不能代替后端权限。</p>
<h3 class="mt-8 text-xl font-semibold text-white">4.5 测试和部署</h3>
<p class="mt-3 leading-7 text-mist-300">在项目根目录执行：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[5]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">数据库测试需要 <code>TEST_DATABASE_URL</code> 指向允许创建临时数据库的测试 PostgreSQL；未配置会跳过数据库用例，不要把生产库作为测试库。部署使用项目现有流程，包含新的 <code>build</code>、源码及 <code>drizzle</code> 迁移目录，然后重启 Warcon。Docker 安装可按仓库 Compose 配置重新构建、启动。启动迁移 <code>0065_personal_plugins</code> 创建配置表。</p>
<p class="mt-3 leading-7 text-mist-300">登录新版本，打开“个人插件”，选择“使用：我的概况”，关联服务器并保存，即完成安装。</p>
<h2 class="mt-8 text-xl font-semibold text-white">5. HTTP API</h2>
<p class="mt-3 leading-7 text-mist-300">以下路径相对于 Warcon 面板域名；不直接访问游戏 RCON。成功返回 JSON 和 <code>ok: true</code>，失败为 <code>ok: false</code> 及 <code>error.message</code>、<code>error.code</code>。所有数据响应禁用缓存。</p>
<h3 class="mt-8 text-xl font-semibold text-white">5.1 个人配置 API：使用登录会话</h3>
<div class="table-wrap mt-4"><table><thead><tr><th>方法</th><th>路径</th><th>用途</th></tr></thead><tbody><tr><td>GET</td><td><code>/api/plugins</code></td><td>列出当前账号配置，返回 <code>plugins</code></td></tr><tr><td>POST</td><td><code>/api/plugins</code></td><td>安装配置，201，返回 <code>plugin</code></td></tr><tr><td>GET</td><td><code>/api/plugins/&#123;pluginId&#125;</code></td><td>查看本人配置</td></tr><tr><td>PUT</td><td><code>/api/plugins/&#123;pluginId&#125;</code></td><td>完整替换清单、关联服务器及启用状态</td></tr><tr><td>DELETE</td><td><code>/api/plugins/&#123;pluginId&#125;</code></td><td>删除本人配置</td></tr><tr><td>GET</td><td><code>/api/plugins/&#123;pluginId&#125;/data</code></td><td>读取已启用插件关联的数据，返回 <code>apiVersion: 1</code>、<code>snapshot</code></td></tr></tbody></table></div>
<p class="mt-3 leading-7 text-mist-300">写请求使用 <code>Content-Type: application/json</code> 和 <code>x-requested-with: warcon</code>。需要浏览器登录 Cookie；组织 Bearer API Key 不能修改个人配置。每次读取服务器数据都重新检查权限。未启用插件的数据接口返回 409 <code>plugin_disabled</code>。未关联服务器返回 <code>snapshot: null</code>。</p>
<p class="mt-3 leading-7 text-mist-300">POST / PUT 请求格式：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[6]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">PUT 是完整替换，不是 PATCH；编辑时不能更换 <code>manifest.id</code>。想复制插件，使用新的 id 发 POST。同一账号 id 重复返回 409 <code>plugin_exists</code>；超 20 个返回 409 <code>plugin_limit</code>；格式错误返回 400 <code>invalid_plugin</code>；上传超过 64 KB 返回 413。</p>
<p class="mt-3 leading-7 text-mist-300">在面板源码里使用既有客户端，它自动携带会话与 CSRF 请求头：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[7]}</code></pre>
<h3 class="mt-8 text-xl font-semibold text-white">5.2 外部客户端：使用组织 API Key</h3>
<p class="mt-3 leading-7 text-mist-300">读接口：<code>GET /api/servers/&#123;serverId&#125;/plugin-snapshot</code>。</p>
<p class="mt-3 leading-7 text-mist-300">创建有 <code>server.view</code> 权限、限定目标服务器范围的组织 API Key，在自己的后端保存；通过 <code>Authorization: Bearer ...</code> 请求。浏览器中运行的内置插件使用上面的会话接口，不把 Bearer Key 发给客户浏览器。</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[8]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">独立 Node / Bun 客户端示例：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[9]}</code></pre>
<p class="mt-3 leading-7 text-mist-300">响应示例（说明结构用的示例数值）：</p>
<pre class="mt-4 overflow-x-auto rounded border border-white/10 bg-ink-950 p-4 text-xs leading-6"><code>{snippets[10]}</code></pre>
<p class="mt-3 leading-7 text-mist-300"><code>stale</code> 表示玩家快照缺失或超过 90 秒；<code>statusAt</code> 单独表示地图状态时间。数据来自 Worker 最近采样，调用这个接口不会强制游戏服务器重新采集。建议客户端至少间隔 10 秒、避免并发轮询，失败时停止显示旧数据并显示错误。缺字段或 <code>null</code> 应显示“—”。不返回 RCON 地址／密码、Feed 令牌、Steam Key 或 AI Key。</p>
<h2 class="mt-8 text-xl font-semibold text-white">6. 常见问题</h2>
<p class="mt-3 leading-7 text-mist-300">- <strong>JSON 导入成功却没有数字</strong>：先关联服务器，确认插件已启用、账号有权限，且 Worker 已采集玩家列表。</p>
<p class="mt-3 leading-7 text-mist-300">- <strong>显示旧数据</strong>：检查页面的快照时间和过期提示；这个插件接口不负责修复游戏连接。</p>
<p class="mt-3 leading-7 text-mist-300">- <strong>代码插件找不到</strong>：检查两个注册表的 renderer 是否一致，确认服务器已部署新构建并重启。</p>
<p class="mt-3 leading-7 text-mist-300">- <strong>导入另一个人的 JSON 无权看他的服务器</strong>：需要自行选择有权限的服务器，导入文件不授予权限。</p>
<p class="mt-3 leading-7 text-mist-300">- <strong>样式没有变化</strong>：JSON 卡片读取全部 style 字段；代码组件需自己使用相应 props，示例代码组件仅使用强调色。</p>
<p class="mt-3 leading-7 text-mist-300">- <strong>名称改了没生效</strong>：JSON 编辑后先点“应用 JSON 到表单”，再保存；优先级以表单为准。</p>
</main>
